Repository testground/sdk-go, pull requests merged in 2020-05, with the labels that each got.

#11 pacify go vet.
  runtime/metrics_types.go
Labels: bug

#10 tests: fix races.
  runtime/influxdb_batch_test.go
  sync/barrier_test.go
  sync/gc_test.go
  sync/generic_client_test.go
  sync/topic_test.go
Labels: bug

#15 update influxdb schema for diagnostics
  runtime/metrics.go
  runtime/metrics_types.go
  runtime/runenv_test.go
Labels: approved

#14 add resetting histogram type and resetting counter type
  runtime/metrics.go
  runtime/metrics_api.go
  runtime/metrics_types.go
  runtime/resetting_counter.go
  runtime/resetting_histogram.go
  runtime/resetting_histogram_test.go
  runtime/runenv_test.go
Labels: approved

#17 fix histogram.Mean deadlock
  runtime/resetting_histogram.go
Labels: bug

#16 initial impl of in-mem sync client for testing.
  network/client.go
  sync/barrier_test.go
  sync/client.go
  sync/client_inmem.go
  sync/client_state.go
  sync/client_sugar.go
  sync/interface.go
Labels: approved

#18 do not resolve redis IP, but rather pass hostname to redis.Client opts
  sync/client.go
  sync/redis_test.go
Labels: waiting for review
